#!/usr/bin/python3

import os, argparse, subprocess

# parse arguments
parser = argparse.ArgumentParser()
parser.add_argument("fasm", metavar="input.s", help="the MIPS assembly file (ASCII)")
args = parser.parse_args()

fasm = args.fasm
fhex = os.path.splitext(args.fasm)[0] + ".x"

# run SPIM (the actual MIPS assembler)
# SPIM = "/afs/ece/class/ece447/bin/spim447"
SPIM = "/Users/chathurgudesa/Desktop/Courses/cmu_18_447_spring_2015/labs/spimsimulator-code/spim/spim"
cmd = [SPIM, "-notrap", "-assemble", fasm, fhex]
subprocess.call(cmd)

# SPIM outputs many files; but we are interested in only one
cmd = ["mv", fhex + ".out", fhex]
subprocess.call(cmd)

# remove unnecessary two lines from the file
lines = open(fhex).readlines()
data = lines[1]
data = str.join('\n', [l.strip() for l in data.split(",") if (l.strip() != "0x0" and l.strip().startswith("0x"))])
open(fhex, 'w').write(data)

# remove all other files
# cmd = ["rm", fasm + ".out"]
# cmd = str.join(' ', cmd)
# subprocess.call(cmd, shell=True)  # we need a shell to expand the wildcard

